apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-cfg
  labels:
    name: prometheus-server-cfg
data:
  prometheus.yml: |-
    global:
        scrape_interval: 5s
        evaluation_interval: 5s
    rule_files:
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'app-svc:80' ]