apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    type: app
    kind: svc
spec:
  selector:
    app: prometheus
    type: app
  ports:
    - port: 9090
      targetPort: 9090
      name: backend-port
      nodePort: 32001
  type: NodePort
