global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
#      todo как собирать метрики с двух инстансов одновременно
      - targets: ['app-svc:8080']


