apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    type: deployment
    app: carService
    kind: db
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: carService
      type: postgres-db
  template:
    metadata:
      labels:
        app: carService
        type: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          imagePullPolicy: Never
#    todo env file
          ports:
            - containerPort: 5432
              protocol: TCP
              name: postgres-port
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
