apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: spring-lab2
    type: app
    kind: svc
spec:
  selector:
    app: spring-lab2
    type: app
  ports:
    - port: 80
      targetPort: 8080
      name: backend-port
      nodePort: 32003
  type: NodePort