apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deployment
  labels:
    type: sts
    app: postgres-db
    kind: db
spec:
  selector:
    matchLabels:
      app: postgres-db
  serviceName: db-service
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: postgres-db
          image: postgres:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
              protocol: TCP
              name: postgres-port
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: db-config
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: db-config
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: db-config
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
#      volumes:
#        - name: postgres-data
#          persistentVolumeClaim:
#            claimName: postgres-pvc
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: manual
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    type: service
    app: carService
    kind: db
spec:
  type: ClusterIP
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: postgres-port
      protocol: TCP
      name: postgres-service-port