apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '3000'
spec:
  selector:
    app: carService
    type: grafana-ui
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000